### ISSUE TITLE
Dropdown items parent issue

### ISSUE THREAD

**Issue by AndreLesa** [BlueCodeSystems/nacmis#64]
This issue is to track all the dropdown related issues even those that have their own issue.

- [x] Update all dropdowns to alphabetical order #61 
- [x] Make the dropdows searchable #62 
- [x] All dropdowns that include "‘Other- please specify" should have a text field just after the dropdown

**Comment by AndreLesa** [comment]
Add a new field called question_other. It will be editable by the stakeholder as a charfield and should be a sub number under the question

**Comment by kaykabwe** [comment]
Resolved
